const data = {
  products: [
    {
      name: "Draken Pattern Tee (Oversize Drop-Shoulder)",
      id: 'skljfkldjf',
      slug: "draken-pattern-tee",
      category: "tees",
      price: 949.0,
      rating: 4.93,
      numberOfReviews: 14,
      stock: 65,
      description:
        "65 GSM, Poly-Cotton Blend Fabric, Pre-Shrunk & Bio-Washed Fabric",
      images: [
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
      ],
    },
    {
      name: "Draken Pattern Tee (Oversize Drop-Shoulder)",
      id: 'ksjdfkldsjfkl',
      slug: "draken-pattern-tee",
      category: "tees",
      price: 949.0,
      rating: 4.93,
      numberOfReviews: 14,
      stock: 65,
      description:
        "65 GSM, Poly-Cotton Blend Fabric, Pre-Shrunk & Bio-Washed Fabric",
      images: [
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
      ],
    },
    {
      name: "Draken Pattern Tee (Oversize Drop-Shoulder)",
      id: 'skfjkldjf',
      slug: "draken-pattern-tee",
      category: "tees",
      price: 949.0,
      rating: 4.93,
      numberOfReviews: 14,
      stock: 65,
      description:
        "65 GSM, Poly-Cotton Blend Fabric, Pre-Shrunk & Bio-Washed Fabric",
      images: [
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
      ],
    },
    {
      name: "Draken Pattern Tee (Oversize Drop-Shoulder)",
      id: 'sfkdsjfklj',
      slug: "draken-pattern-tee",
      category: "tees",
      price: 949.0,
      rating: 4.93,
      numberOfReviews: 14,
      stock: 65,
      description:
        "65 GSM, Poly-Cotton Blend Fabric, Pre-Shrunk & Bio-Washed Fabric",
      images: [
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
      ],
    },
    {
      name: "Draken Pattern Tee (Oversize Drop-Shoulder)",
      id: 'ksjfkldjfsgy',
      slug: "draken-pattern-tee",
      category: "tees",
      price: 949.0,
      rating: 4.93,
      numberOfReviews: 14,
      stock: 65,
      description:
        "65 GSM, Poly-Cotton Blend Fabric, Pre-Shrunk & Bio-Washed Fabric",
      images: [
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
      ],
    },
    {
      name: "Draken Pattern Tee (Oversize Drop-Shoulder)",
      id: 'kdljfkldsjf',
      slug: "draken-pattern-tee",
      category: "tees",
      price: 949.0,
      rating: 4.93,
      numberOfReviews: 14,
      stock: 65,
      description:
        "65 GSM, Poly-Cotton Blend Fabric, Pre-Shrunk & Bio-Washed Fabric",
      images: [
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
        "/images/draken-oversize1_comicsense-3.webp",
      ],
    },
  ],
};

export { data };
